# Build this django app as a python package
# and upload it to our package registry/repo.
#
# See also https://gitlab.sissamedialab.it/wjs/wjs-utils-project/-/blob/master/.gitlab-ci.yml

default:
  image: python

variables:
  # CI_API_V4_URL: The GitLab API v4 root URL.
  # CI_PROJECT_ID: The ID of the current project.

  # Project 60 is *OMlPI*
  # Open Medialab Package Index - a public repository of software for our packages
  PACKAGE_REGISTRY_PROJECT_ID: 60

  TWINE_PASSWORD: ${CI_JOB_TOKEN}
  TWINE_USERNAME: "gitlab-ci-token"

# Not running any tests (at the moment), because they require a
# working installation of Janeway, with this django app installed.
stages:
  - build

build-job:
  stage: build
  rules:
     if: $CI_PIPELINE_SOURCE == "push" && $CI_COMMIT_BRANCH == "master"
  script:
    - python setup.py sdist bdist_wheel
    - pip install twine
    - python -m twine upload --repository-url ${CI_API_V4_URL}/projects/${PACKAGE_REGISTRY_PROJECT_ID}/packages/pypi dist/*
    - echo "Package successfully published."
