default:
  image: python:3.9
  # Default runner tag
  tags:
    - inasset

variables:
  PACKAGE_NAME: 'wjs.jcom_profile'

# Not running any tests (at the moment), because they require a
# working installation of Janeway, with this django app installed.
stages:
  - test
  - build
  - deploy


include:
  - project: 'wjs/wjs-profile-project'
    ref: master
    file: '.gitlab-ci-pkg-build-and-upload.yml'
  - project: 'wjs/wjs-profile-project'
    ref: master
    file: '.gitlab-ci-pkg-deploy-to-test.yml'
  - project: 'wjs/wjs-profile-project'
    file: '.gitlab-ci-run-tests.yml'


run-tests:
  # Always run tests, except for tags, which have tests already run on
  # them when the commit is made.
  except:
    - tags

  extends:
    - .run-tests

upload-package:
  only:
    - tags

  extends:
    - .upload-package

deploy-to-test:
  only:
    - tags

  extends:
    - .deploy-to-test

  # Deploy basically means `pip install`, so the package must already
  # be in the package registry.
  needs:
    - upload-package
