.deploy-to-pp:

  stage: deploy

  variables:
    VENV_BIN: "/home/wjs/.virtualenvs/j-pp/bin"
    PYTHON: "${VENV_BIN}/python"
    PIP: "${VENV_BIN}/pip"
    # touch this file to restart the uwsgi server
    UWSGI_VASSAL: "/home/wjs/uwsgi/janeway-pp.ini"

  script:
    - echo "Deploy to pre-production server"
    - chmod og= $ID_RSA
    - ssh -i $ID_RSA -o StrictHostKeyChecking=no $SERVER_USER@$SERVER_IP "(cd janeway-pp && $PIP install --index-url=$PIP_INDEX_URL -U $PACKAGE_NAME && cd src && ../finalize-deploy.sh $PYTHON && touch --no-dereference $UWSGI_VASSAL )"
