deploy-to-test:
  stage: deploy

  variables:
    PIP: "/home/wjs/.virtualenvs/j1-venv/bin/pip"
    PIP_INDEX_URL: "https://gitlab.sissamedialab.it/api/v4/projects/60/packages/pypi/simple"
    # touch this file to restart the uwsgi server
    UWSGI_VASSAL: "/home/wjs/uwsgi/janeway.ini"

  script:
    - echo "Deploy to testing server"
    - chmod og= $ID_RSA
    - ssh -i $ID_RSA -o StrictHostKeyChecking=no $SERVER_USER@$SERVER_IP "( cd janeway && $PIP install --index-url=$PIP_INDEX_URL -U $PACKAGE_NAME && touch --no-dereference $UWSGI_VASSAL )"

  only:
    feature/task-20-autodeploy-packages
    # - tags
