.run-tests:
  stage: test

  image: registry.gitlab.sissamedialab.it/wjs/wjs-profile-project/debian-python-git-janeway

  # TODO: Must match with test_settings.DATABASES
  variables:
    POSTGRES_USER: janeway
    POSTGRES_PASSWORD: janeway
    POSTGRES_DB: janeway
    DJANGO_SETTINGS_MODULE: core.test_settings
    GIT_STRATEGY: clone
    GIT_CHECKOUT: "true"

  services:
    - name: ${CI_DEPENDENCY_PROXY_GROUP_IMAGE_PREFIX}/postgres:13.8
      alias: db

  script:
    - git checkout feature/task-20-autodeploy-packages
    - cp test_settings.py /janeway/src/core
    - pip install ./[test]
    - cd /janeway/src
    - pytest -c ${CI_PROJECT_DIR}/pytest.ini ${CI_PROJECT_DIR}/ -v -x


# lintme:
#   extends: .run-tests
