.test:
  veriables:
    per postgre? TBV (check image documentation)
    DB_USER...
    DB_PASSWD...

  services:
    - postgres:13.8

  script:
    - git clone janeway
    - setup venv
    - prepare settings module
      - with my package in  INSTALLED_APPS
      - with middleware
      - with postgres things
    - make install_janeway
    - pip install package


# write docker compose? OR connect to local postgresql (verify local postgres binding - no only localhost)
# run image and work in container
# mount in bind le dir di J. e pacchetto
# refine script (setup and co)
