default:
  image: python:3.9
  # Default runner tag
  tags:
    - inasset

variables:
  PACKAGE_NAME: 'wjs.jcom_profile'

# Not running any tests (at the moment), because they require a
# working installation of Janeway, with this django app installed.
stages:
  - build
  - deploy

include:
  - project: 'wjs/wjs-profile-project'
    ref: feature/task-20-autodeploy-packages
    file: '.gitlab-ci-pkg-build-and-upload.yml'
  - project: 'wjs/wjs-profile-project'
    ref: feature/task-20-autodeploy-packages
    file: '.gitlab-ci-pkg-deploy-to-test.yml'
