.deploy:

  stage: deploy

  # Need these variables to be defined:
  # The `bin` folder of the virtualenv
  # e.g.: VENV_BIN: "/home/wjs/.virtualenvs/j-pp/bin"
  #
  # The "vassal" file for uwsgi to reload
  # e.g.:  UWSGI_VASSAL: "/home/wjs/uwsgi/janeway-pp.ini"
  #
  # Server (and ssh user) to deploy to $SERVER_USER@$SERVER_IP
  # e.g.: SERVER_IP: "janeway-test"
  #       SERVER_USER: "wjs"
  variables:
    PYTHON: "${VENV_BIN}/python"
    PIP: "${VENV_BIN}/pip"

  script:
    - echo "Deploy to pre-production server"
    - chmod og= $ID_RSA
    - ssh -i $ID_RSA -o StrictHostKeyChecking=no $SERVER_USER@$SERVER_IP "(cd janeway-pp && $PIP install --index-url=$PIP_INDEX_URL -U $PACKAGE_NAME && cd src && ../finalize-deploy.sh $PYTHON && touch --no-dereference $UWSGI_VASSAL )"
