# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
exclude: "(.idea|node_modules|.tox)"
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files
      - id: check-builtin-literals
      - id: check-executables-have-shebangs
      - id: check-merge-conflict
      - id: check-toml
      - id: fix-encoding-pragma
        args:
          - --remove
  - repo: https://github.com/PyCQA/isort
    rev: 5.12.0
    hooks:
      - id: isort
  - repo: https://github.com/psf/black
    rev: 23.1.0
    hooks:
      - id: black
  - repo: https://github.com/pycqa/flake8
    rev: 5.0.2
    hooks:
      - id: flake8
        additional_dependencies:
          - flake8-broken-line
          - flake8-bugbear
          - flake8-builtins
          - flake8-commas
          - flake8-comprehensions
          - flake8-eradicate
          - pep8-naming
  - repo: https://github.com/asottile/pyupgrade
    rev: v3.3.1
    hooks:
      - id: pyupgrade
        args:
          - --py3-plus
  - repo: https://github.com/PyCQA/pydocstyle
    rev: 6.3.0
    hooks:
      - id: pydocstyle
        additional_dependencies:
          - toml
        exclude: |
          (?x)(
              ^wjs/jcom_profile/migrations/|
              ^^wjs/jcom_profile/tests/
          )
  - repo: https://github.com/Riverside-Healthcare/djLint
    rev: v1.19.16
    hooks:
      - id: djlint-django
