# Generated by Django 1.11.29 on 2022-11-10 12:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jcom_profile", "0006_auto_20221110_1133"),
    ]

    operations = [
        migrations.AlterField(
            model_name="editorassignmentparameters",
            name="editor",
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name="editorassignmentparameters",
            name="keywords",
            field=models.ManyToManyField(through="jcom_profile.EditorKeyword", to="submission.Keyword"),
        ),
    ]
