# Generated by Django 1.11.29 on 2022-11-25 15:25

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("jcom_profile", "0006_auto_20221116_1538"),
    ]

    operations = [
        migrations.AddField(
            model_name="specialissue",
            name="invitees",
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
