# Generated by Django 1.11.29 on 2022-11-30 15:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("jcom_profile", "0007_auto_20221118_1311"),
    ]

    operations = [
        migrations.AddField(
            model_name="specialissue",
            name="invitees",
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name="articlewrapper",
            name="special_issue",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="articles",
                to="jcom_profile.SpecialIssue",
            ),
        ),
        migrations.AlterField(
            model_name="editorassignmentparameters",
            name="keywords",
            field=models.ManyToManyField(blank=True, through="jcom_profile.EditorKeyword", to="submission.Keyword"),
        ),
    ]
