# Generated by Django 1.11.29 on 2022-11-30 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("submission", "0069_delete_blank_keywords"),
        ("jcom_profile", "0007_auto_20221118_1311"),
    ]

    operations = [
        migrations.AddField(
            model_name="specialissue",
            name="allowed_sections",
            field=models.ManyToManyField(to="submission.Section"),
        ),
        migrations.AlterField(
            model_name="editorassignmentparameters",
            name="keywords",
            field=models.ManyToManyField(blank=True, through="jcom_profile.EditorKeyword", to="submission.Keyword"),
        ),
    ]
