# Generated by Django 1.11.29 on 2022-11-25 16:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jcom_profile", "0007_specialissue_invitees"),
    ]

    operations = [
        migrations.AlterField(
            model_name="articlewrapper",
            name="special_issue",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="articles",
                to="jcom_profile.SpecialIssue",
            ),
        ),
    ]
