# Generated by Django 1.11.29 on 2022-12-22 10:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("journal", "0055_issue_isbn"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("jcom_profile", "0012_auto_20221216_2208"),
    ]

    operations = [
        migrations.CreateModel(
            name="NewsletterTopic",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("topic", models.CharField(max_length=50, verbose_name="Newsletter topic")),
            ],
            options={
                "verbose_name": "topic",
                "verbose_name_plural": "Newsletter topics",
            },
        ),
        migrations.CreateModel(
            name="Recipient",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("news", models.BooleanField(default=False, verbose_name="Generic news topic")),
                (
                    "journal",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="journal.Journal",
                        verbose_name="Newsletter topics' journal",
                    ),
                ),
                (
                    "topics",
                    models.ManyToManyField(
                        blank=True, to="jcom_profile.NewsletterTopic", verbose_name="Newsletters topics"
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Newsletter topics user",
                    ),
                ),
            ],
            options={
                "verbose_name": "recipient",
                "verbose_name_plural": "recipients",
            },
        ),
    ]
